---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Get the IP of the kubernetes cluster
      shell: "kubectl cluster-info | grep master | grep -o 'http.*:[0-9]*'"
      register: kubernetes_ip

    - debug: msg="{{ kubernetes_ip.stdout }}"

    - name: Run the spark program
      command: "spark-2.4.0-bin-hadoop2.7/bin/spark-submit \
          --master k8s://{{ kubernetes_ip.stdout }} \
          --deploy-mode cluster \
          --name spark-pi \
          --class org.apache.spark.examples.SparkPi \
          --conf spark.executor.instances=2 \
          --driver-memory=1g \
          --executor-memory=1g \
          --conf spark.kubernetes.container.image=docker.io/theipple/spark \
          local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
