---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Get the IP of the kubernetes cluster
      shell: "kubectl cluster-info | grep master | grep -o 'http.*:[0-9]*'"
      register: kubernetes_ip

    - debug: msg="{{ kubernetes_ip.stdout }}"

    - name: Run the spark program
      shell: "nohup spark-2.4.0-bin-hadoop2.7/bin/spark-submit \
          --master k8s://{{ kubernetes_ip.stdout }} \
          --deploy-mode cluster \
          --name spark-kafka-mongo \
          --class SimpleApp \
          --conf spark.executor.instances=2 \
          --driver-memory=1g \
          --executor-memory=1g \
          --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
          --conf spark.kubernetes.container.image=docker.io/theipple/spark \
          https://s3.eu-west-3.amazonaws.com/sdtdk8s/simple-project-1.0-jar-with-dependencies.jar </dev/null >/dev/null 2>&1 &"

    - debug: msg="see the result on the logs of the driver node"
