kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-kafka-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafkadata1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-kafka-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafkadata2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-kafka-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafkadata3"
---
