---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Copy zookeeper pv
      copy:
          src: ./zookeeper-pv.yaml
          dest: /tmp/zookeeper-pv.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Create zookeeper persistent volume
      command: kubectl apply -f /tmp/zookeeper-pv.yaml

    - name: Copy zookeeper deploy
      copy:
          src: ./zookeeper-deploy.yaml
          dest: /tmp/zookeeper-deploy.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Create zookeeper cluster
      command: kubectl apply -f /tmp/zookeeper-deploy.yaml

    - name: Get Wanted zk pods
      command: sh -c "kubectl describe statefulset zk | grep -Po '(?<=ZK_REPLICAS:.{11})(.*)$'"
      register: WantedZookeeperPods

    - name: Wait zk pods to run
      shell: sh -c "kubectl describe statefulset zk | grep -Po '(?<=Pods Status:.{8})(.*)(?= Running)'"
      register: RunningZookeeperPods
      changed_when: False
      until: RunningZookeeperPods.stdout == WantedZookeeperPods.stdout
      retries: 20
      delay: 5

    - name: Copy kafka pv
      copy:
          src: ./kafka-pv.yaml
          dest: /tmp/kafka-pv.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Create kafka persistent volume
      command: kubectl apply -f /tmp/kafka-pv.yaml

    - name: Copy kafka deploy
      copy:
          src: ./kafka-deploy.yaml
          dest: /tmp/kafka-deploy.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Create kafka cluster
      command: kubectl apply -f /tmp/kafka-deploy.yaml

    - name: Get Wanted kafka pods
      command: sh -c "kubectl describe statefulset kafka | grep -Po -m 1 '(?<=\"replicas\":)([0-9]+)'"
      register: WantedKafkaPods

    - name: Wait kafka pods to run
      shell: sh -c "kubectl describe statefulset kafka | grep -Po '(?<=Pods Status:.{8})(.*)(?= Running)'"
      register: RunningKafkaPods
      changed_when: False
      until: RunningKafkaPods.stdout == WantedKafkaPods.stdout
      retries: 20
      delay: 5
