kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafkadata1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafkadata2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafkadata3"
---
