kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-zk-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zookeeperdata1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-zk-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zookeeperdata2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-zk-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zookeeperdata3"
---
