---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Install the dashboard
      command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

    - name: example copying file with owner and permissions
      copy:
        src: "{{item}}"
        dest: "{{item}}"
      loop:
        - dashboard-admin.yml
        - service-account.yml

    - name: Give permissions to the dashboard
      command: kubectl apply -f dashboard-admin.yml

    - name: start kubectl proxy in background
      shell: nohup kubectl proxy --address 0.0.0.0 --accept-hosts '.*' </dev/null >/dev/null 2>&1 &

    - debug:
        msg: "To see the webui, start a reverse proxy with 'ssh -NL 8001:127.0.0.1:8001 {{ ansible_user }}@{{ ansible_host }}' \
        http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/"

    - name: Retreive token to access the dashboard
      shell: "kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep kubernetes-dashboard-token | awk '{print $1}') | grep token:"
      register: token_output

    - debug:
        msg: "Use the token to login in the dashboard \n{{ token_output.stdout }}"
