---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Copy mongo pv
      copy:
          src: ./mongo-pv.yaml
          dest: /tmp/mongo-pv.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Create mongodb persistent volume
      command: kubectl apply -f /tmp/mongo-pv.yaml

    - name: Copy mongo deployment
      copy:
          src: ./mongo-deploy.yaml
          dest: /tmp/mongo-deploy.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Create mongodb cluster
      command: kubectl apply -f /tmp/mongo-deploy.yaml

    - name: Get Wanted pods
      command: sh -c "kubectl describe statefulset mongo | grep -Po '(?<=desired.{3})(.*)(?= total)'"
      register: WantedMongoPods

    - name: Wait pods to run
      shell: sh -c "kubectl describe statefulset mongo | grep -Po '(?<=Pods Status:.{8})(.*)(?= Running)'"
      register: RunningMongoPods
      changed_when: False
      until: RunningMongoPods.stdout == WantedMongoPods.stdout
      retries: 20
      delay: 5

    - name: Copy mongo initialization commands file
      copy:
          src: ./mongo_init_cmd
          dest: /tmp/mongocfg
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Setup mongo replicas set
      command: sh -c "kubectl exec -it mongo-0 mongo < /tmp/mongocfg"
