---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Generate a new token to join the cluster
      command: kubeadm token create --print-join-command
      register: join_command


- hosts: k8s_slaves
  gather_facts: no
  vars:
    join_cmd: "{{ hostvars.master.join_command.stdout }}"
  tasks:
    - debug: var=join_cmd

    - name: Join the kubernetes cluster
      become: true
      command: "{{ join_cmd }}"
    # - name: Get $HOME
    #   command: echo $HOME
    #   register: HOME
    #
    # - name: Create .kube folder
    #   file: path="{{ HOME.stdout }}/.kube" state=directory
    #   # shell: mkdir -p $HOME/.kube
    #
    # - name: stat .kube/config
    #   stat: path="{{ HOME.stdout }}/.kube/config"
    #   register: kube_config
    #
    # - name: Copy /etc/kubernetes/admin.conf to $HOME/.kube/conf
    #   become: true
    #   command: "cp /etc/kubernetes/admin.conf {{ HOME.stdout }}/.kube/config"
    #   when: not kube_config.stat.exists
    #
    # - name: Get $(id -u):$(id -g)
    #   command: echo $(id -u):$(id -g)
    #   register: user_group
    #   when: not kube_config.stat.exists
    #
    # - name: Change owner of the file $HOME/.kube/
    #   become: true
    #   file:
    #     path: "{{ HOME.stdout }}/.kube/config"
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
      # become: true
      # command: "chown {{ user_group.stdout }} {{ HOME.stdout }}/.kube/config"
      # when: not kube_config.stat.exists

    # - file:
    #     path: $HOME/.kube/config
    #     state: file
    #     owner: foo
    #     group: foo
    #     mode: 0644
#
#     - name:
#       become: true
#       shell: cp /etc/kubernetes/admin.conf $HOME/.kube/config
#
#     - name:
#       become: true
#       shell: chown $(id -u):$(id -g) $HOME/.kube/config
#
#     - name:
#       become: true
#       shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#
#     - name:
#       become: true
#       shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
