kind: Pod
apiVersion: v1
metadata:
  name: web-server
spec:
  containers:
    - name: web-server
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      ports:
        - containerPort: 80
  restartPolicy: Never
