---
- hosts: k8s_master
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file
      copy:
        src: default
        dest: /etc/nginx/sites-enabled/default
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
