---
- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Copy web-server deployement file
      copy:
          src: ./apache-deploy.yaml
          dest: /tmp/apache-deploy.yaml
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Deploy the web server
      command: kubectl apply -f /tmp/apache-deploy.yaml

    - name: Wait web-server pod to run
      shell: sh -c "kubectl describe pods web-server | grep -Po '(?<=Status:).*' | sed 's/ //g'"
      register: WebServerStatus
      changed_when: False
      until: WebServerStatus.stdout == "Running"
      retries: 20
      delay: 5

    - name: Create web-server service
      command: kubectl create service nodeport web-server --tcp=80:80

    - name: Copy apache initialization commands file
      copy:
          src: ./setup_apache_cmd
          dest: /tmp/setup_apache_cmd
          owner: ubuntu
          group: ubuntu
          mode: u=rw,g=r,o=r

    - name: Setup apache server on pod
      command: sh -c "kubectl exec -it web-server bash < /tmp/setup_apache_cmd"
