---
- hosts: localhost
  vars:
    aws_region: eu-west-3
  environment:
    BOTO_USE_ENDPOINT_HEURISTICS: True
  gather_facts: no
  connection: local
  tasks:

    - name: Get instances
      ec2_instance_facts:
        filters:
          tag:instance_type: k8s-ansible
          instance-state-name: pending
          instance-state-name: running
      register: ec2_instances

    # - debug: var=ec2_instances

    # - debug: msg="{{ ec2_instances.instances | map(attribute='instance_id') | list }}"

    - name: Resiliate running instances (tagged k8s-ansible)
      ec2:
        region: "{{ aws_region }}"
        instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"
        state: absent
        wait: yes
      when: ec2_instances.instances | length > 0
